version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Backend service (uncomment when ready)
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   restart: unless-stopped

  # Celery worker (uncomment when ready)
  # worker:
  #   build: ./backend
  #   command: celery -A app.tasks.celery_app worker --loglevel=info
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   restart: unless-stopped

  # Celery beat scheduler (uncomment when ready)
  # beat:
  #   build: ./backend
  #   command: celery -A app.tasks.celery_app beat --loglevel=info
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   restart: unless-stopped

volumes:
  redis_data:
